export const CATEGORY={
    VIEW_RESTUARANTS:' VIEW_RESTUARANTS',
    
    CHANGE_CATEGORY_NAME:'CHANGE_CATEGORY_NAME',
    CHANGE_CATEGORY_IMAGES:'CHANGE_CATEGORY_IMAGES',
    SAVE_CATEGORY_CHANGES:'SAVE_CATEGORY_CHANGES',
    GET_CATEGORY_DATA_SUCCESS:'GET_CATEGORY_DATA_SUCCESS',
    GET_CATEGORY_DATA_ERROR:'GET_CATEGORY_DATA_ERROR',
    GET_CATEGORY_DATA_LOADING:'GET_CATEGORY_DATA_LOADING',
    GET_CATEGORY_DATA_API:'GET_CATEGORY_DATA_API',

    DELETE_CATEGORY:' DELETE_CATEGORY',
    DELETE_CATEGORY_SUCCESS:'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR:'DELETE_CATEGORY_ERROR',

    SET_CATEGORY_DATA_API:'SET_CATEGORY_DATA_API',
    SET_DATA_ERROR:'SET_DATA_ERROR',
    SET_DATA_SUCCESS:'SET_DATA_SUCCESS',
    SET_DATA_LOADING:'SET_DATA_LOADING',

    EDIT_CATEGORY_API:'EDIT_CATEGORY_API',
    EDIT_CATEGORY_SUCCESS:'EDIT_CATEGORY_SUCCESS',
    EDIT_CATEGORY_ERROR:'EDIT_CATEGORY_ERROR',
    EDIT_CATEGORY_LOADING:'EDIT_CATEGORY_LOADING',

    SET_INITIAL:'SET_INITIAL'
};