export const ORDERS={
    // VIEW_RESTUARANTS:' VIEW_RESTUARANTS',
    
    // CHANGE_CATEGORY_NAME:'CHANGE_CATEGORY_NAME',
    // CHANGE_CATEGORY_IMAGES:'CHANGE_CATEGORY_IMAGES',
    // SAVE_CATEGORY_CHANGES:'SAVE_CATEGORY_CHANGES',
    GET_ORDER_DATA_SUCCESS:'GET_ORDER_DATA_SUCCESS',
    GET_ORDER_DATA_ERROR:'GET_ORDER_DATA_ERROR',
    GET_ORDER_DATA_LOADING:'GET_ORDER_DATA_LOADING',
    GET_ORDER_DATA_API:'GET_ORDER_DATA_API',

    DELETE_CATEGORY:' DELETE_CATEGORY',
    DELETE_CATEGORY_SUCCESS:'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR:'DELETE_CATEGORY_ERROR',

    SET_CATEGORY_DATA_API:'SET_CATEGORY_DATA_API',
    SET_DATA_ERROR:'SET_DATA_ERROR',
    SET_DATA_SUCCESS:'SET_DATA_SUCCESS',
    SET_DATA_LOADING:'SET_DATA_LOADING',

    CHANGE_ORDER_STATUS:'CHANGE_ORDER_STATUS',
    
 
    ORDER_STATUS_UPDATE:'ORDER_STATUS_UPDATE',
    ORDER_STATUS_UPDATE_LOADING:'ORDER_STATUS_UPDATE_LOADING',
    ORDER_STATUS_UPDATE_ERROR:'ORDER_STATUS_UPDATE_ERROR',
    ORDER_STATUS_UPDATE_SUCCESS:'ORDER_STATUS_UPDATE_SUCCESS',

    SET_INITIAL:'SET_INITIAL'
};